export const STATE_APPORTIONMENT: Record<number, { name: string; districts: number }> = {
  1: { name: "Alabama", districts: 7 },
  2: { name: "Alaska", districts: 1 },
  4: { name: "Arizona", districts: 9 },
  5: { name: "Arkansas", districts: 4 },
  6: { name: "California", districts: 52 },
  8: { name: "Colorado", districts: 8 },
  9: { name: "Connecticut", districts: 5 },
  10: { name: "Delaware", districts: 1 },
  11: { name: "District of Columbia", districts: 1 }, // Non-voting
  12: { name: "Florida", districts: 28 },
  13: { name: "Georgia", districts: 14 },
  15: { name: "Hawaii", districts: 2 },
  16: { name: "Idaho", districts: 2 },
  17: { name: "Illinois", districts: 17 },
  18: { name: "Indiana", districts: 9 },
  19: { name: "Iowa", districts: 4 },
  20: { name: "Kansas", districts: 4 },
  21: { name: "Kentucky", districts: 6 },
  22: { name: "Louisiana", districts: 6 },
  23: { name: "Maine", districts: 2 },
  24: { name: "Maryland", districts: 8 },
  25: { name: "Massachusetts", districts: 9 },
  26: { name: "Michigan", districts: 13 },
  27: { name: "Minnesota", districts: 8 },
  28: { name: "Mississippi", districts: 4 },
  29: { name: "Missouri", districts: 8 },
  30: { name: "Montana", districts: 2 },
  31: { name: "Nebraska", districts: 3 },
  32: { name: "Nevada", districts: 4 },
  33: { name: "New Hampshire", districts: 2 },
  34: { name: "New Jersey", districts: 12 },
  35: { name: "New Mexico", districts: 3 },
  36: { name: "New York", districts: 26 },
  37: { name: "North Carolina", districts: 14 },
  38: { name: "North Dakota", districts: 1 },
  39: { name: "Ohio", districts: 15 },
  40: { name: "Oklahoma", districts: 5 },
  41: { name: "Oregon", districts: 6 },
  42: { name: "Pennsylvania", districts: 17 },
  44: { name: "Rhode Island", districts: 2 },
  45: { name: "South Carolina", districts: 7 },
  46: { name: "South Dakota", districts: 1 },
  47: { name: "Tennessee", districts: 9 },
  48: { name: "Texas", districts: 38 },
  49: { name: "Utah", districts: 4 },
  50: { name: "Vermont", districts: 1 },
  51: { name: "Virginia", districts: 11 },
  53: { name: "Washington", districts: 10 },
  54: { name: "West Virginia", districts: 2 },
  55: { name: "Wisconsin", districts: 8 },
  56: { name: "Wyoming", districts: 1 }
};
